[package]
name = "wbtech-task00"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7.6"
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
serde = { version = "1.0.210", features = ["derive"] }